apiVersion: v1
kind: ConfigMap
metadata:
  name: lmcache-hyperpod-config
data:
  config.yaml: |
    chunk_size: 256
    local_cpu: true
    max_local_cpu_size: 4
    save_unfull_chunk: true
    extra_config:
      sagemaker_hyperpod_shared_memory_name: ai_toolkit_cache
